[package]
name = "html-transformer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
html5ever = "0.27.0"
markup5ever = "0.12.0"
markup5ever_rcdom = "0.3.0"
rusttype = "0.9.3"
xml5ever = "0.18.0"
